# version: '3.8'

services:
  web:
    build: ./packd
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./packd/:/usr/src/packd/
    ports:
      - 8000:8000
    env_file:
      - ./packd/.env.dev